messages:
  # Obecné
  prefix: "&8&l[&e!&8] &e&lEvent &8▪ &r"
  no_permission: "&cNemáš oprávnění."
  config_reloaded: "&fConfig úspěšně reloadován!"
  help: "&6MultiShuffle - Použití: /is nebo /bs"
  command_usage: "&ePoužití: /<command> <start|stop|skip>"
  invalid_argument: "&cNeznámý argument."

  # Stavy hry
  game_started: "&fHra byla <green>spuštěna&f."
  game_stopped: "&fHra byla <red>ukončena&f."
  game_already_running: "&fHra již běží!"
  no_game_running: "&fŽádná hra aktuálně &cneběží&f."
  round_skipped: "&fKolo bylo &epřeskočeno<white>!"

  # Průběh hry
  target_found: "&fNašel jsi &8(&e<target>&8)&f a získáváš bod! Nyní počkej na další kolo."
  target_broadcast: "&fHráč &a<player>&f našel svůj item &8(&e<target>&8)"

  # Odpočty a vyhlašování
  countdown_title: ""
  countdown_subtitle: "&e<time>s"
  game_ending: "<white>Hra skončila! Počítám výherce..."
  place_1: "<gold>1. místo</gold>"
  place_2: "<gray>2. místo</gray>"
  place_3: "<color:#cd7f32>3. místo</color>"
  place_format: "<place> <white><player></white> - <yellow><points><white> bodů!"

  # Hodnoty Placeholderů
  placeholder_finished: "<green>Splněno</green>"
  placeholder_ability_active: "&eAktivní"
  placeholder_none: "&cN/A"

game:
  default_round_time: 300
  announcement_delay: 2
  default_rounds: 5

lists:
  use_as_whitelist: true
items:
  - "minecraft:apple"
  - "minecraft:bread"
  - "minecraft:iron_ingot"
  - "minecraft:gold_ingot"
  - "minecraft:diamond"
  - "minecraft:coal"
  - "minecraft:stick"
  - "minecraft:bone"
  - "minecraft:gunpowder"
  - "minecraft:string"
  - "minecraft:feather"
  - "minecraft:flint"
  - "minecraft:leather"
  - "minecraft:spider_eye"
  - "minecraft:rotten_flesh"
  - "minecraft:wheat_seeds"
  - "minecraft:wheat"
  - "minecraft:sugar_cane"
  - "minecraft:sugar"
  - "minecraft:egg"
  - "minecraft:clay_ball"
  - "minecraft:snowball"
  - "minecraft:copper_ingot"
  - "minecraft:raw_iron"
  - "minecraft:raw_copper"
  - "minecraft:raw_gold"
  - "minecraft:lapis_lazuli"
  - "minecraft:redstone"
  - "minecraft:flint_and_steel"
  - "minecraft:bowl"
  - "minecraft:mushroom_stew"
  - "minecraft:suspicious_stew"
  - "minecraft:beef"
  - "minecraft:cooked_beef"
  - "minecraft:porkchop"
  - "minecraft:cooked_porkchop"
  - "minecraft:mutton"
  - "minecraft:cooked_mutton"
  - "minecraft:chicken"
  - "minecraft:cooked_chicken"
  - "minecraft:rabbit"
  - "minecraft:cooked_rabbit"
  - "minecraft:rabbit_hide"
  - "minecraft:salmon"
  - "minecraft:cod"
  - "minecraft:sweet_berries"
  - "minecraft:glow_berries"
  - "minecraft:kelp"
  - "minecraft:dried_kelp"
  - "minecraft:melon_slice"
  - "minecraft:melon_seeds"
  - "minecraft:pumpkin_seeds"
  - "minecraft:carrot"
  - "minecraft:potato"
  - "minecraft:baked_potato"
  - "minecraft:wooden_sword"
  - "minecraft:wooden_shovel"
  - "minecraft:wooden_pickaxe"
  - "minecraft:wooden_axe"
  - "minecraft:wooden_hoe"
  - "minecraft:stone_sword"
  - "minecraft:stone_shovel"
  - "minecraft:stone_pickaxe"
  - "minecraft:stone_axe"
  - "minecraft:stone_hoe"
  - "minecraft:iron_sword"
  - "minecraft:iron_shovel"
  - "minecraft:iron_pickaxe"
  - "minecraft:iron_axe"
  - "minecraft:iron_hoe"
  - "minecraft:leather_helmet"
  - "minecraft:leather_chestplate"
  - "minecraft:leather_leggings"
  - "minecraft:leather_boots"
  - "minecraft:iron_helmet"
  - "minecraft:iron_chestplate"
  - "minecraft:iron_leggings"
  - "minecraft:iron_boots"
  - "minecraft:shield"
  - "minecraft:bucket"
  - "minecraft:water_bucket"
  - "minecraft:lava_bucket"
  - "minecraft:milk_bucket"
  - "minecraft:shears"
  - "minecraft:oak_boat"
  - "minecraft:birch_boat"
  - "minecraft:spruce_boat"
  - "minecraft:arrow"
  - "minecraft:bow"
  - "minecraft:glass_bottle"
  - "minecraft:paper"
  - "minecraft:book"
  - "minecraft:painting"
  - "minecraft:item_frame"
  - "minecraft:flower_pot"
  - "minecraft:bone_meal"
  - "minecraft:white_dye"
  - "minecraft:red_dye"
  - "minecraft:yellow_dye"
  - "minecraft:blue_dye"
  - "minecraft:light_blue_dye"
  - "minecraft:pink_dye"
  - "minecraft:orange_dye"
  - "minecraft:black_dye"
  - "minecraft:brown_dye"
  - "minecraft:green_dye"
  - "minecraft:clock"
  - "minecraft:compass"
  - "minecraft:spyglass"

blocks:
  - "minecraft:grass_block"
  - "minecraft:dirt"
  - "minecraft:coarse_dirt"
  - "minecraft:rooted_dirt"
  - "minecraft:mud"
  - "minecraft:cobblestone"
  - "minecraft:stone"
  - "minecraft:smooth_stone"
  - "minecraft:diorite"
  - "minecraft:granite"
  - "minecraft:andesite"
  - "minecraft:tuff"
  - "minecraft:calcite"
  - "minecraft:dripstone_block"
  - "minecraft:sand"
  - "minecraft:red_sand"
  - "minecraft:gravel"
  - "minecraft:sandstone"
  - "minecraft:oak_log"
  - "minecraft:birch_log"
  - "minecraft:spruce_log"
  - "minecraft:jungle_log"
  - "minecraft:acacia_log"
  - "minecraft:dark_oak_log"
  - "minecraft:cherry_log"
  - "minecraft:mangrove_log"
  - "minecraft:oak_planks"
  - "minecraft:birch_planks"
  - "minecraft:spruce_planks"
  - "minecraft:jungle_planks"
  - "minecraft:acacia_planks"
  - "minecraft:dark_oak_planks"
  - "minecraft:cherry_planks"
  - "minecraft:oak_leaves"
  - "minecraft:birch_leaves"
  - "minecraft:spruce_leaves"
  - "minecraft:crafting_table"
  - "minecraft:furnace"
  - "minecraft:chest"
  - "minecraft:barrel"
  - "minecraft:smoker"
  - "minecraft:blast_furnace"
  - "minecraft:stonecutter"
  - "minecraft:loom"
  - "minecraft:composter"
  - "minecraft:campfire"
  - "minecraft:torch"
  - "minecraft:ladder"
  - "minecraft:scaffolding"
  - "minecraft:glass"
  - "minecraft:glass_pane"
  - "minecraft:white_wool"
  - "minecraft:light_gray_wool"
  - "minecraft:gray_wool"
  - "minecraft:black_wool"
  - "minecraft:brown_wool"
  - "minecraft:white_bed"
  - "minecraft:red_bed"
  - "minecraft:white_carpet"
  - "minecraft:oak_stairs"
  - "minecraft:cobblestone_stairs"
  - "minecraft:oak_slab"
  - "minecraft:cobblestone_slab"
  - "minecraft:oak_fence"
  - "minecraft:oak_fence_gate"
  - "minecraft:oak_door"
  - "minecraft:iron_door"
  - "minecraft:oak_trapdoor"
  - "minecraft:iron_trapdoor"
  - "minecraft:oak_pressure_plate"
  - "minecraft:stone_pressure_plate"
  - "minecraft:oak_button"
  - "minecraft:stone_button"
  - "minecraft:lever"
  - "minecraft:redstone_torch"
  - "minecraft:pumpkin"
  - "minecraft:carved_pumpkin"
  - "minecraft:jack_o_lantern"
  - "minecraft:melon"
  - "minecraft:hay_block"
  - "minecraft:dirt_path"
  - "minecraft:farmland"
  - "minecraft:cobweb"
  - "minecraft:dandelion"
  - "minecraft:poppy"
  - "minecraft:blue_orchid"
  - "minecraft:allium"
  - "minecraft:azure_bluet"
  - "minecraft:red_tulip"
  - "minecraft:orange_tulip"
  - "minecraft:white_tulip"
  - "minecraft:pink_tulip"
  - "minecraft:oxeye_daisy"
  - "minecraft:cornflower"
  - "minecraft:lily_of_the_valley"
  - "minecraft:sunflower"
  - "minecraft:lilac"
  - "minecraft:rose_bush"
  - "minecraft:peony"
  - "minecraft:tall_grass"
  - "minecraft:large_fern"
  - "minecraft:sugar_cane"
  - "minecraft:kelp"
  - "minecraft:moss_block"
  - "minecraft:moss_carpet"
  - "minecraft:azalea"
  - "minecraft:flowering_azalea"
  - "minecraft:clay"
  - "minecraft:coal_ore"
  - "minecraft:iron_ore"
  - "minecraft:copper_ore"
  - "minecraft:gold_ore"
  - "minecraft:lapis_ore"
  - "minecraft:redstone_ore"
  - "minecraft:diamond_ore"
  - "minecraft:raw_iron_block"
  - "minecraft:raw_copper_block"
  - "minecraft:iron_block"
  - "minecraft:copper_block"
  - "minecraft:coal_block"
  - "minecraft:magma_block"
  - "minecraft:netherrack"
  - "minecraft:basalt"
  - "minecraft:blackstone"
  - "minecraft:soul_sand"
  - "minecraft:soul_soil"

abilities:
  enabled: false
  rewards:
    - "SPEED:2:30"
    - "JUMP_BOOST:1:15"

# Konfigurace obou scoreboardů
scoreboards:
  enabled: true
  item_shuffle:
    title: "<color:#ffaa00><b>ItemShuffle</b>"
    lines:
      - "<dark_gray>--------------------</dark_gray>"
      - "&fČas: &d%multishuffle_time%"
      - "&fKolo: &e%multishuffle_round%&f/&6%multishuffle_maxround%</white>"
      - "&fBody: <gold>%multishuffle_points%</gold>"
      - ""
      - "&fItem: <green>%multishuffle_item%</green>"
      - "<dark_gray>--------------------</dark_gray>"
  block_shuffle:
    title: "<color:#ffaa00><b>BlockShuffle</b>"
    lines:
      - "<dark_gray>--------------------</dark_gray>"
      - "&fČas: &d%multishuffle_time%"
      - "&fKolo: &e%multishuffle_round%&f/&6%multishuffle_maxround%</white>"
      - "&fBody: <gold>%multishuffle_points%</gold>"
      - ""
      - "&fBlok: <green>%multishuffle_item%</green>"
      - "<dark_gray>--------------------</dark_gray>"