name: MultiShuffle
version: '1.0.0'
main: cz.xoam24.multishuffle.MultiShuffle
api-version: '1.21'
authors: [xoam24]
description: Komplexní kombinace ItemShuffle a BlockShuffle!

depend:
  - PlaceholderAPI

commands:
  ms:
    description: MultiShuffle admin příkazy
    usage: /ms <reload|points>
    permission: multishuffle.admin
  is:
    description: ItemShuffle příkazy
    usage: /is <start|stop|skip|mode>
    permission: multishuffle.admin
  bs:
    description: BlockShuffle příkazy
    usage: /bs <start|stop|skip|mode>
    permission: multishuffle.admin

permissions:
  multishuffle.admin:
    description: Přístup ke všem MultiShuffle příkazům
    default: op