name: MultiShuffle
version: 1.0.0
main: cz.xoam24.multishuffle.MultiShuffle
api-version: '1.21'
depend: [PlaceholderAPI]
authors: [xoam24]

commands:
  ms:
    description: Hlavni příkaz pro MultiShuffle (reload, help)
    permission: multishuffle.admin
  is:
    description: Příkazy pro ItemShuffle
    permission: multishuffle.admin
  bs:
    description: Příkazy pro BlockShuffle
    permission: multishuffle.admin

permissions:
  multishuffle.admin:
    description: Umoznuje spravovat a spoustet hry.
    default: op