name: MultiShuffle
version: 1.0.0
main: cz.xoam24.multishuffle.MultiShuffle
api-version: '1.21'
depend: [PlaceholderAPI]
authors: [xoam24]
description: Komplexni kombinace ItemShuffle a BlockShuffle!

commands:
  ms:
    description: Hlavni prikaz pro MultiShuffle (reload, help)
    permission: multishuffle.admin
  is:
    description: Prikazy pro ItemShuffle
    permission: multishuffle.admin
  bs:
    description: Prikazy pro BlockShuffle
    permission: multishuffle.admin

permissions:
  multishuffle.admin:
    description: Umoznuje spravovat a spoustet hry.
    default: op